apiVersion: v1
kind: Service
metadata:
  name: {{ include "sampleapi.fullname" . }}
  labels:
    {{- include "sampleapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
      nodePort: 31200
  selector:
    {{- include "sampleapi.selectorLabels" . | nindent 4 }}
